name: ldb_qr_payment
description: Flutter plugin for LDB QR Payment Lao Development Bank
repository: https://github.com/PitiDev/ldb_qr_payment
author: Piti Phanthasombath
version: 1.0.0
homepage: https://www.pitidev.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
   http: ^0.13.5
   encrypt: ^5.0.1
   pointycastle: ^3.6.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

